#version: '3.8'

services:
  server1:
    container_name: server1
    build:
      context: alpine/cluster/.
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.101
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server2:
    container_name: server2
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.102
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server3:
    container_name: server3
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.103
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server4:
    container_name: server4
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.104
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  haproxy:
    container_name: haproxy
    build: alpine/haproxy/.
    networks:
      cluster:
        ipv4_address: 172.100.0.200
      monitor:
        ipv4_address: 172.200.0.200

  prometheus:
    container_name: prometheus
    build: alpine/prometheus/.
    networks:
      monitor:
        ipv4_address: 172.200.0.210

networks:
  cluster:
#    network_name: cluster
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
  monitor:
#    network_name: monitor
    driver: bridge
    ipam:
       config:
        - subnet: 172.200.0.0/24
