#version: '3.8'

services:
  server1:
    container_name: server1
    build:
      context: alpine/cluster/.
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.101

  server2:
    container_name: server2
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.102

  server3:
    container_name: server3
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.103

  server4:
    container_name: server4
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.104

  server5:
    container_name: server5
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.105

#Creamos o haproxy
  haproxy:
    container_name: haproxy
    build: alpine/haproxy/.
    networks:
      cluster:
        ipv4_address: 172.100.0.200
      monitor:
        ipv4_address: 172.200.0.200

#Creamos o prometheus
  prometheus:
    container_name: prometheus
    build: alpine/prometheus/.
    networks:
      monitor:
        ipv4_address: 172.200.0.210

#Creamos as redes
networks:
  cluster:
#    network_name: cluster
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
  monitor:
#    network_name: monitor
    driver: bridge
    ipam:
       config:
        - subnet: 172.200.0.0/24
