version: '3.8'

services:
  server1:
    build: Alpine/.
    networks:
      mynet:
        ipv4_address: 172.100.0.101
#    volumes:
#      - ~/archivos/index.php:/var/www/htdocs/index.php
#      - ~/archivos/httpd.conf:/etc/apache2/httpd.conf

  server2:
    build: Alpine/.
    networks:
      mynet:
        ipv4_address: 172.100.0.102
#    volumes:
#      - ~/archivos/index.php:/var/www/htdocs/index.php
#      - ~/archivos/httpd.conf:/etc/apache2/httpd.conf

  server3:
    build: Alpine/.
    networks:
      mynet:
        ipv4_address: 172.100.0.103
#    volumes:
#      - ~/archivos/index.php:/var/www/htdocs/index.php
#      - ~/archivos/httpd.conf:/etc/apache2/httpd.conf

  server4:
    build: Alpine/.
    networks:
      mynet:
        ipv4_address: 172.100.0.104
#    volumes:
#      - ~/archivos/index.php:/var/www/htdocs/index.php
#      - ~/archivos/httpd.conf:/etc/apache2/httpd.conf

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
