#version: '3.8'

services:
  server1:
    build:
      context: Alpine/Cluster/.
    image: alpine-cluster
    networks:
      cluster:
        ipv4_address: 172.100.0.101
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server2:
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.102
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server3:
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.103
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server4:
    image: alpine-cluster
    pull_policy: never
    networks:
      cluster:
        ipv4_address: 172.100.0.104
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  haproxy:
    build: Alpine/HAProxy/.
    networks:
      cluster:
        ipv4_address: 172.100.0.200
      monitor:
        ipv4_address: 172.200.0.200

networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
  monitor:
    driver: bridge
    ipam:
       config:
        - subnet: 172.200.0.0/24
