#version: '3.8'

services:
  server1:
    build: Alpine/.
    networks:
      cluster:
        ipv4_address: 172.100.0.101
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server2:
    build: Alpine/.
    networks:
      cluster:
        ipv4_address: 172.100.0.102
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server3:
    build: Alpine/.
    networks:
      cluster:
        ipv4_address: 172.100.0.103
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

  server4:
    build: Alpine/.
    networks:
      cluster:
        ipv4_address: 172.100.0.104
#    command: sh -c "ip route del default && ip route add default via 172.100.0.200 && httpd -D FOREGROUND"

networks:
  cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 172.100.0.0/24
