groups:
- name: haproxy.alerts
  rules:
  # Moitas peticións
  - alert: HAProxyHighRequestRate
    expr: haproxy:http_requests:rate30s > 6
    for: 30s
    labels:
      severity: warning
    annotations:
      description: "HAProxy está recivindo {{ $value }} peticións cada 30s"

  # Servidor de Backup en uso
  - alert: HAProxyBackupServerInUse
    expr:  haproxy_backend_active_servers{instance="172.200.0.200:9090", job="haproxy", proxy="sitio_web1"} == 0
    for: 30s
    labels:
      severity: warning
    annotations:
      description: "Servidor backend 'server5' para web1 en uso"
